UNC-Libraries/jitterbug

- app/Import/ItemsImport.php
- resources/views/items/_items-import-table-header.blade.php
- resources/views/items/_items-import-upload-data.blade.php
This allows for the ReelTapeNumber column to be populated by batch CSV upload.
The CSV preview now shows the column:
The resulting item has the column populated:
I'm checking in about possible validations, but the upload works.
> APPDEV-7507 adding CSV upload ability for ReelTapeNumber

- app/Models/CallNumberSequence.php
- tests/TestCase.php
- tests/Unit/CallNumberSequenceTest.php
This PR adds a few tests for the `next` method in CallNumberSequences which has the logic for what type of call number should be used when creating a new item.
> Appdev 8583 call number test

- public/css/app.css
- public/js/app.js
- public/js/router.js
- resources/views/dashboard/_marks.blade.php
- resources/views/dashboard/index.blade.php
This PR contains functionality for deleting multiple marks at a time from the Jitterbug dashboard. A user may select all, or a few marks at a time via checkbox. The checkboxes and delete button will only show up if the current user is the same as the user of the listed marks. There is a confirmation with the number of marks to delete.
I cleaned up the `initSelectAll` function used for selecting all fields to export and made it reusable. In doing so, I fixed a bug in which the select all functionality would not work if the server is too slow.
> Appdev 6551 delete multiple marks

- app/Http/Requests/CollectionRequest.php
- app/Models/Collection.php
- resources/views/admin/_collections.blade.php
This PR makes it possible to see the archival identifer on collections and edit it. You can now also add the archival identifier when making a new collection.
> APPDEV-8722 archival identifier form and column in collections admin index

- database/migrations/2019_07_22_180603_add_archival_identifier_to_new_call_number_sequences.php
- database/seeds/AddArchivalIdentifierSeederToCollections.php
- database/seeds/AddArchivalIdentifierToCallNumbersSeeder.php
- database/seeds/AddArchivalIdentifierToCollectionsSeeder.php
This PR includes the migration for the new archival_identifier column in new call number sequences. There is also a seeder for this column. I also reworked the old archival identifier seeder for collections so that it can be re-run without affecting records that have already been filled in.
I also removed the references to the models in the seeder because i read that it was best practice to not do that.
> Appdev 8733 new column for new call number sequences

- Homestead.yaml.example
- app/Http/Controllers/Admin/CollectionsController.php
- app/Http/Requests/CollectionRequest.php
- app/Models/Collection.php
- composer.json
- database/migrations/2019_08_23_194815_change_collection_id_column_to_autoincrement.php
- database/seeds/AddArchivalIdentifierToCallNumbersSeeder.php
- database/seeds/AddArchivalIdentifierToCollectionsSeeder.php
- resources/views/admin/_collections.blade.php
This PR makes the ID column on collections an auto-incrementing column. This includes scripts that:
1. loop through all collections and set their IDs sequentially
2. adjust the collection_id column of new_call_number_sequences
3. adjust the collection_id column of audio_visual items
Because of this, the ability to specify the ID by users has been removed when creating new collections and the ID column in the front end has been removed since it's now not related to the finding aid ID.
> Appdev 8779 auto incrementing collection ids

- app/Import/ItemsImport.php
This PR fixes the validation so that it correctly passes in the collection ID, which it finds via the archival identifier.
> APPDEV-8641 fixing bug with collection ID instead of archival identifier

- .circleci/config.yml
- app/Http/Controllers/Admin/CollectionsController.php
- app/Models/Collection.php
When adding new collections, it was discovered that the mechanism to create new call numbers was missing the collection's ID. Previously, when it was not auto-incrementing, the ID was specified so it was included in the newly created collection's attributes. Now, it is set by the DB when saved. 
This PR removed the ID column from the $fillable attributes array and removed the line that said not to auto-increment the ID (which was no longer working anyway).
> APPDEV-9038 find collection ID via query

- app/Http/Controllers/Admin/CollectionsController.php
- resources/views/admin/_collections.blade.php
When creating a new collection, it was incorrectly displaying the collection type name of the previous first column instead of its own. This adds the info to the json response so that the view can display the correct info.
> APPDEV-9039 added collection type name to json response

- app/Http/Requests/ItemRequest.php
When specifying the batch option, if no batch size is provided, then the form should flash a message (see screen shot).
It looks like the request is specifying batchSize but the error handling is looking for batch_size. so the flash message doesn't work. It just redirects back to the form with no other messaging. This PR fixes that.
> APPDEV-9228 fixing the flash message that wasn't showing up

- .circleci/config.yml
- after.sh
the `mysql-connector-java-8.0.17.zip` is no longer available so this changes the package to a newer version
> updating mysql connector file

- app/Http/Requests/ItemRequest.php
- app/Import/ItemsImport.php
- database/factories/ModelFactory.php
- database/migrations/2020_02_12_190752_change_accession_number_to_string.php
This PR includes the migration to change the accession_number column from integer to string, since the accession numbers coming from ArchivesSpace now look like "20200110.1" instead of whole numbers.
The validations and factories are also adjusted to accommodate this change.
> Appdev 9263 accession number migration

- app/Import/AudioImport.php
- app/Models/Transfer.php
- tests/Feature/TransferAudioImportsTest.php
- tests/import-test-files/audio-import/small_upload_file_no_errors.csv
This PR includes the code necessary for the TrackConfiguration column in audio imports upload. The front end, the CSV upload and validation, executing the change in the DB, and a test.
> APPDEV-9355 added track config to transfer audio imports upload

- app/Import/AudioImport.php
- app/Models/Transfer.php
- database/factories/ModelFactory.php
- tests/Feature/TransferAudioImportsTest.php
- tests/import-test-files/audio-import/small_upload_file_no_errors.csv
This PR adds speed to the batch transfer audio items import. Now it checks whether the object is dirty before saving, since the audio item or the audio visual item might be changed. Also the items core in solr is updated if any of the audio visual items have been changed.
I've also removed some unnecessary ID specifications in the factories and added a new test.
> APPDEV-add speed to audio imports

- app/Import/AudioImport.php
This PR removes the solr update because speed is not indexed by solr, so any changes to that column do not require solr to be updated.
> Appdeb 9357 remove solr update

- app/Models/Transfer.php
An uppercase M should be a lowercase m to match code in audio transfers import upload.
> APPDEV-9494 fixing typo that caused OriginalPm bug

- database/migrations/2020_05_20_191648_add_import_action_to_import_transactions_table.php
This is the migration to add the new column "import_action" to the import_transactions table. This will be used to record whether the import was a create or update.
> APPDEV-9522 migration file for import action column

- app/Console/Commands/BackfillImportActions.php
This PR contains the script for looping through all ~730 import transactions and setting the import_action to 'update' if appropriate. It loops through the related revisions (by transaction_id) and scans the fields that were changed in the revision.
If any of the fields are 'created_at' then the import was a create. If none of the fields are 'created_at' then it was an update. In the VM DB there are only seven of these, which lines up with what Erica has mentioned about the frequency of update imports.
> Appdev 9523 import action backfill script

- app/Models/Activity.php
- app/Presenters/TransactionDigest.php
This PR fixes two bugs:
- the activity object determination was dependent on the old "imported" action which now no longer applies, because the import action is now "created via import" or "updated via import". also DRYed up the logic
- the count previously only counted PreservationMaster revisions. now that the new columns have been added to the import that affect AudioVisualItems and AudioItems, those are now included
> Appdev 9524 update transaction digest for update imports

- app/Presenters/TransactionDigest.php
- composer.json
- database/factories/ModelFactory.php
This typo was preventing the ActivityStream from generating correctly. It fixes the error found in the log:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'numFields' in 'field list'`
> APPDEV-9628 fixing camelCased field name to snake_case

- app/Models/AudioItem.php
- app/Models/AudioVisualItem.php
- database/migrations/2020_07_08_183918_add_blank_to_audio_visual_items.php
- resources/views/items/_form-common.blade.php
- resources/views/items/show.blade.php
- tests/Unit/AudioVisualItemTest.php
This PR adds the migration for a new column, "blank" on audio visual items. For the front end, we needed a function that would display "yes" or "no" depending on the boolean value. This function would be used on the show page (via attribute magic) and would also be used by Revisionable code to display the corresponding revisions when the values are changed.
> Appdev 8481 blank check box av items

- app/Console/Commands/SetCollectionToLegacyCallNumberSequence.php
This PR is for a script that will take a specified archival identifier and then find all new_call_number_sequences related to that archival identifier. 
For those new_call_number_sequences that have been used (where the "next" number isn't 1) it will collect the associated prefix into an array.
For those new_call_number_sequences that haven't been used, it will delete them.
The reason it will delete them is to force the call number generator to use the legacy call number sequence pattern instead. For example, for archival identifier 20188, a new call number sequence for prefix FT would be FT-20188/1. A legacy call number might be something like FT-1988. For certain collections we want it to follow legacy generation.
> Appdev 9593 legacy collection script

- app/Http/Controllers/Admin/FormatsController.php
- public/js/app.js
- resources/views/admin/_formats.blade.php
It was reported that when making a new format, what was listed under the prefixes was incorrect. Also the "Edit Prefixes" button led to a completely blank page.
It turns out that the ajax success takes the first format in the list, copies it, and replaces what it knows with the new format's fields. In this case there are not any connected prefixes yet so it just shows that model format's prefixes. This PR replaces it with a note to edit prefixes. 
As for the blank page, that was the result of old laravel route helper syntax. Once that was updated, the page now loads again.
> Appdev 9805 formats prefix bug

- .circleci/config.yml
- after.sh
- app/Http/Requests/FormatRequest.php
- app/Models/Format.php
- app/Models/Prefix.php
- composer.json
- database/factories/ModelFactory.php
- database/migrations/2020_10_14_155824_delete_prefix_and_legacy_prefix_from_formats_table.php
- resources/views/admin/_formats.blade.php
- tests/Unit/CallNumberSequenceTest.php
Last summer, the prefix-format relational structure of Jitterbug was updated to be a many-to-many relationship so now is the time to remove the prefix and legacy prefix columns from formats and any related code. There is a migration to remove the columns, removal of front-end code and validations, and an adjusted scope function. Lastly, one test and one factory were edited to accommodate this change.
> Appdev 8643 delete columns

- config/cache.php
- config/filesystems.php
- config/session.php
- config/view.php
This PR allows a storage path to be set on the server using the `.env` file variable `STORAGE_PATH`. If it's not set, it will use the local storage path.
> Change storage config based on env file

- app/Export/Export.php
- app/Http/Controllers/ItemsController.php
- app/Http/Controllers/TransfersController.php
If `STORAGE_PATH` is specified in the `.env` file, store upload and export files there
> Upload and export storage now accounts for .env storage path

- Homestead.yaml.example
- README.md
- Vagrantfile
- after.sh
- composer.lock
This PR updates the base Homestead box from 6.4.0 to 10.1.0. This was necessary to update a few things, including node version. 6.4.0 was necessary when Jitterbug was still on PHP 5.4 but that is no longer the case.
> Appdev 9895 updating homestead

- app/Support/SolariumProxy.php
- database/seeders/UsersTableSeeder.php
- solrconfig/jitterbug-items/conf/managed-schema
- solrconfig/jitterbug-masters/conf/managed-schema
- solrconfig/jitterbug-transfers/conf/managed-schema
After the sorting functionality was released, users noticed that sorting of titles and notes were not as alphabetical as they expected. It turns out that the field used in solr for these columns were great for searching (every word is tokenized) but not for sorting.
This PR introduces new solr fields that use the "lowercase" field type so that when sorted by these fields, results show up in a more logical manner for that sort.
Also includes a small edit to a seeder that was noticed after repopulating the VM DB.
> Appdev 9994 solr config change for sorting

- database/factories/PreservationInstanceFactory.php
- routes/web.php
- tests/Browser/SelectAllTest.php
This PR fixes bugs that Erica identified:
- Batch editing in Preservation Instances leads to Error page
- Batch export in Preservation Instances leads to empty window 
- Issue of Control+A and Control+Select not working across multiple pages in table
It also adds a browser test for the select all functionality, as this is the third time that's had to be fixed.
> Appdev 10000 preservation instance

- routes/web.php
There was one last place in the preservation instances routing config that should have been plural instead of singular. This PR fixes that, and therefore also fixes the 500 error encountered in https://jira.lib.unc.edu/browse/APPDEV-10091
> APPDEV-10091 fixing hopefully the last instances-related routing problem

- app/Http/Controllers/InstancesController.php
- app/Import/AudioImport.php
- app/Import/VideoImport.php
- app/Support/SolariumProxy.php
- public/js/app.js
- resources/views/items/_preservation_instance_filter.blade.php
- resources/views/items/index.blade.php
- solrconfig/jitterbug-items/conf/managed-schema
- solrconfig/jitterbug-items/conf/solr-data-config.xml
This PR introduces a new filter for the AV Items index: the preservation instances filter. If an AV Item has a related preservation instance, that means it has been digitized, so this new filter allows the user to see which items have been digitized and which have not. It works in concert with the other filters, the search bar, and the pagination.
> Appdev 6818 pi designated av items

- app/Import/AudioImport.php
- tests/Feature/TransferAudioImportsTest.php
- tests/import-test-files/audio-import/sample_audio_import_update_missing_headers.csv
This PR fixes/actually allows there to be missing headers when the audio import is an update (instead of making new records). There was already logic in the validations for this, but the execution step still depended on the existence of the required fields when processing the CSV.
This PR:
- checks to see if required fields are set, first
- adds a validation that if AV item fields are filled, call number field must also exist and be filled in
- adds two tests
- fixes some spacing in the tests file
> Appdev 8654 import columns optional

- .env.dusk.testing
- Homestead.yaml.example
- README.md
This PR details a few config changes to make sure that Dusk is using the testing DB when run. It also adds necessary changes to Homestead.yaml.example so that Dusk can be run after setting up a new VM.
> Appdev 10195 fix dusk

- app/Http/Controllers/Admin/AdminController.php
- public/js/app.js
- tests/Feature/AdminTest.php
This PR implements a controller check to make sure that inactive users cannot be made admin. This is already precluded by the front-end, but having a back end check makes it more secure.
> Appdev 9782 validation and error handling for admin users

- Homestead.yaml.example
- Vagrantfile
- composer.lock
Needed to update the homestead base box to get around debian bintray error:
```
jitterbug-php-8: E: The repository 'https://dl.bintray.com/rabbitmq-erlang/debian bionic Release' no longer has a Release file.
jitterbug-php-8: E: The repository 'https://dl.bintray.com/rabbitmq/debian bionic Release' no longer has a Release file.
```
https://unclibrary.atlassian.net/browse/BXC-4172
> Bxc 4172 update jitterbug vm

- app/Models/BatchAudioVisualItem.php
- app/Models/BatchPreservationInstance.php
- app/Models/BatchTransfer.php
Remove parent__construct call as it seems to also be called when instantiating the specific item type class in the batch constructor, which the batch class inherits from.
https://unclibrary.atlassian.net/browse/APPDEV-11453
> Batch editing fix

- app/Console/Kernel.php
- app/Presenters/ActivityStream.php
- app/Presenters/TransactionDigest.php
This PR does the following:
- adding descending sort order to revisions query
- removing one method call to find the call number to use already set value
- changing query to find the last AV item instead of the first
- updating spacing/indentation
- update truncate to delete
> fix sort order and minimize DB calls
